### ISSUE TITLE
orderbook demo

### ISSUE THREAD

**Issue by jian1098** [i25959341/orderbook#1]
Can you provide an example?

**Comment by nilber** [comment]
I already researched for several, all that I found in Go did not work or
are not complete.
So I'm developing a version for the company where I work. But if your
intention is to have a language independent engine, I've used this
http://paritytrading.com obviously I made changes to my environment and
added a bit more speed in operations, but in a general context it is very
good to platform.

Em qui, 3 de jan de 2019 08:27, jian1098 <notifications@github.com escreveu:

**Comment by jian1098** [comment]
I modified some of the code and ran the test file perfectly.Thanks.

**Comment by i25959341** [comment]
Can you made a PR for the modifications that you have made :) ??

**Comment by i25959341** [comment]
@jian1098  I think this is solved by #2
